## Лабораторная работа №1 | Вариант 2

Выполнил: Ахметшин Б.Р., М8О-303Б-22

### 1. Numpy

In [3]:
import numpy as np

1. Создайте матрицу размером 8х8 и заполните ее шахматным рисунком

In [4]:
np.matrix([
    [0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0]
])

matrix([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])

2. Каков результат выполнения следующих выражений?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [5]:
np.array(0) / np.array(0)

/tmp/ipykernel_8459/873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [6]:
np.array(0) // np.array(0)

/tmp/ipykernel_8459/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [7]:
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_8459/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

3. Создайте матрицу-шахматную доску 8х8 используя функцию `tile`

In [8]:
np.tile([[0, 1], [1, 0]], (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

4. Как округлить до целых массив чисел с плавающей точкой?

In [9]:
arr = np.random.rand(1, 5)*10
print(arr)
arr = np.floor(arr)
print(arr)

[[1.26312602 2.67733461 2.10495038 5.86790939 1.49043621]]
[[1. 2. 2. 5. 1.]]


5. Как найти общие значения между двумя массивами?

In [10]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6])
print("intersection:", np.intersect1d(a, b))

intersection: [2 4]


6. Как вычислить ((A+B)*(-A/2)) на месте (без копирования)?

In [11]:
a = np.random.rand(1, 5)
b = np.random.rand(1, 5)
c = (a + b)*(-a/2)
print("a:", a)
print("b:", a)
print("c:", c)
b += a 
a /= -2
b *= a
print(np.array_equal(b, c))


a: [[0.8239903  0.61133818 0.07322874 0.88993109 0.56048704]]
b: [[0.8239903  0.61133818 0.07322874 0.88993109 0.56048704]]
c: [[-0.58660201 -0.3149702  -0.01026293 -0.76144535 -0.25887831]]
True


7. Рассмотрим случайный вектор с формой 100х2, представляющей координаты, и найдем расстояния от точки к точке

In [12]:
coords = np.random.random((100, 2))


In [13]:
distances = np.linalg.norm(coords[:, np.newaxis] - coords, axis=2)

distances

array([[0.        , 0.65851739, 0.28944771, ..., 0.7841119 , 0.39529482,
        0.82888624],
       [0.65851739, 0.        , 0.38259009, ..., 0.30682865, 0.26799477,
        0.23959238],
       [0.28944771, 0.38259009, 0.        , ..., 0.57454842, 0.11495823,
        0.58383086],
       ...,
       [0.7841119 , 0.30682865, 0.57454842, ..., 0.        , 0.47366681,
        0.13912884],
       [0.39529482, 0.26799477, 0.11495823, ..., 0.47366681, 0.        ,
        0.47199206],
       [0.82888624, 0.23959238, 0.58383086, ..., 0.13912884, 0.47199206,
        0.        ]])

8. Как конвертировать массив float(32 bit) к массиву целых чисел (integer 32 bit) in place?

In [14]:
a = np.random.rand(1, 10)
a = a.astype(np.int32, copy=False)

9. Создайте структурированный массив, представляющий позицию (x, y) и цвет (r, g, b).

In [15]:
np.array([((0, 0), (100, 100, 100)), ((1, 1), (255, 255, 255))], dtype='2i, 3i')

array([([0, 0], [100, 100, 100]), ([1, 1], [255, 255, 255])],
      dtype=[('f0', '<i4', (2,)), ('f1', '<i4', (3,))])

10. Какой эквивалент enumerate для numpy массивов?

In [16]:
np.ndenumerate(a)

### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом 

Данные о преступлениях, совершенных женщинами в Индии, с демографическими подробностями.

Файл: `CrimesOnWomenData.csv`

```
State - название штата/региона
Year - год записи
Rape - случаи изнасилования
K&A - случаи похищения 
DD - смерти из-за приданого
AoW - нападение на женщин
AoM - нападение на женскую скромность(modestity)
DV - бытовое насилие
WT - торговля женщинами
```

In [17]:
import pandas as pd
pd.set_option("display.precision", 2)

In [18]:
# Load dataset here
DATA_PATH="CrimesOnWomenData.csv"
df = pd.read_csv(DATA_PATH)
df.tail()

Unnamed: 0        State  Year  Rape   K&A   DD   AoW  AoM    DV  WT
731         731   D&N Haveli  2021  1250  4083  141  2068  417  4731   4
732         732  Daman & Diu  2021   315   904   16  1851   10   501   1
733         733     Delhi UT  2021     2     1    0     5    1     9   0
734         734  Lakshadweep  2021     0     0    0     1    1     3   0
735         735   Puducherry  2021     2     0    2    31    3    12   0

1. За какие года представлен набор данных?

In [19]:
year_column = df['Year']
str(np.min(year_column)) + "-" + str(np.max(year_column))

'2001-2021'

2. Выявите район с самым высоким количеством убийств женщин

In [20]:
max_killed_woman = np.max(df['DD'])
df[df['DD'] == max_killed_woman][['State', 'DD']]

State    DD
582  Uttar Pradesh  2524

3. Какое среднее число изнасилований женщин в индии наблюдалось в указанные года?

In [21]:
np.average(df['Rape'])

727.8559782608696

4. Выявите район с минимальным числом похищений за период 2001-2003 года

In [22]:
gb = df[df['Year'].between(2001, 2003)].groupby(['State'])
gb.agg({'K&A' : np.sum}).idxmin()

K&A    LAKSHADWEEP
dtype: object

5. Перечислите районы в которых наблюдались наиболее частые случае домашнего насилия за период с 2005 по 2012 года

In [23]:
gb = df[df['Year'].between(2005, 2012)].groupby(['State'])
gb.agg({'DV' : np.sum}).sort_values(by='DV').tail()

DV
State                
UTTAR PRADESH   42215
MAHARASHTRA     43271
RAJASTHAN       50834
ANDHRA PRADESH  62878
WEST BENGAL     71821

6. Выведите названия районов в порядке не возрастания случаев торговли женщинами за 2020 год

In [24]:
gb = df[df['Year'] == 2020].groupby('State')
gb.agg({'WT' : np.sum}).sort_values(by='WT', ascending=False)

WT
State                 
Sikkim             231
Jharkhand          159
Madhya Pradesh      85
Punjab              67
Uttarakhand         52
Andhra Pradesh      48
Gujarat             47
Bihar               30
Haryana             28
Tripura             25
Nagaland            19
Assam               18
Kerala              14
Tamil Nadu          13
Odisha              11
Uttar Pradesh        8
Karnataka            5
D&N Haveli           3
Chhattisgarh         3
Jammu & Kashmir      2
Telangana            0
Rajasthan            0
Puducherry           0
A & N Islands        0
Lakshadweep          0
Mizoram              0
Meghalaya            0
Manipur              0
Maharashtra          0
Himachal Pradesh     0
Goa                  0
Delhi UT             0
Daman & Diu          0
Chandigarh           0
Arunachal Pradesh    0
West Bengal          0

Перейдем к следующему набору данных.

Файл: `CustomerPurchasingBehaviors.csv`

Этот набор данных содержит информацию о профилях клиентов и их покупательском поведении. Данные содержат столбцы, содержащие идентификатор пользователя, возраст, годовой доход, сумму покупки, показатель лояльности (в разбивке по классам), регион и частоту покупок. Он предназначен для анализа тенденций сегментации клиентов и лояльности и может быть использован для различных задач машинного обучения и анализа данных, связанных с поведением клиентов и исследованиями рынка.

```
user_id - ID клиента
age - Возраст
annual_income - Годовой доход клиента (в долларах США).
purchase_amount - Общая сумма покупок, совершенных клиентом (в долларах США).
loyalty_score - Показатель лояльности клиента (значение от 0 до 100).
region - Регион, в котором проживает клиент (Север, Юг, Восток, Запад).
purchase_frequency - Частота покупок клиентов (количество раз в год).
```

In [25]:
# Load dataset here
df = pd.read_csv('CustomerPurchasingBehaviors.csv')
df.head()

user_id  age  annual_income  purchase_amount  loyalty_score region   
0        1   25          45000              200            4.5  North  \
1        2   34          55000              350            7.0  South   
2        3   45          65000              500            8.0   West   
3        4   22          30000              150            3.0   East   
4        5   29          47000              220            4.8  North   

   purchase_frequency  
0                  12  
1                  18  
2                  22  
3                  10  
4                  13

8. Какой средний годовой доход у клиентов с уровнем лояльности больше 50 живущих на севере \
   (Тут, видимо, ошибка, потому что уровень лояльности клиентов в датасете от 3 до 9.5)

In [26]:
df['loyalty_score'].describe()

count    238.00
mean       6.79
std        1.90
min        3.00
25%        5.50
50%        7.00
75%        8.28
max        9.50
Name: loyalty_score, dtype: float64

In [27]:
df[(df['region'] == 'North') & (5.0 < df['loyalty_score'])]['annual_income'].mean()

60146.34146341463

9. Выведите 25 и 75 перцентили уровня лоальности клиентов живущих на западе с частотой покупок более 20 раз в год

In [28]:
cut = df[(df['region'] == 'West') & (20 < df['purchase_frequency'])]
ls = cut['loyalty_score']
print(ls.quantile(0.25), ls.quantile(0.75))

8.5 9.2


10. Отличается ли медианный возраст клиентов с уровнем лояльности более 70 и менее 10 для жителей Востока и Севера.

In [29]:
cut = df[(df['region'] == 'West') | (df['region'] == 'East')]
cut.describe()
# В датасете нет данных о клиентах с уровнем лояльности меньше 10 :(

user_id    age  annual_income  purchase_amount  loyalty_score   
count    83.00  83.00          83.00            83.00          83.00  \
mean    115.02  43.36       63036.14           496.75           7.73   
std      70.77   8.75        9758.61           123.91           1.61   
min       3.00  22.00       30000.00           150.00           3.00   
25%      52.50  37.00       58000.00           420.00           6.80   
50%     114.00  48.00       68000.00           550.00           8.50   
75%     175.50  50.50       70500.00           600.00           9.00   
max     237.00  55.00       75000.00           640.00           9.50   

       purchase_frequency  
count               83.00  
mean                22.12  
std                  4.00  
min                 10.00  
25%                 20.00  
50%                 24.00  
75%                 25.00  
max                 28.00

### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

In [30]:
import plotly.graph_objects as go
import plotly.express as px

1. Постройте диаграмму которая отражает средний уровень лояльности во всех регионах

In [31]:
average_loyalty_score_by_region = df.groupby('region').agg({'loyalty_score' : np.average})
average_loyalty_score_by_region
fig = go.Figure()
for index, row in average_loyalty_score_by_region.iterrows():
    fig.add_trace(
        go.Bar(x=[row.name], y=[row['loyalty_score']], name=row.name)
    )
fig.update_xaxes(title_text='region')
fig.update_yaxes(title_text='average loyalty score')
fig.show()

2. Постройте гистограмму распределения зарплат клиентов на Севере.

In [32]:
df[df['region'] == 'North']
fig = px.histogram(df, x='annual_income')
fig.show()


3. Сравните уровни зарплат людей на севере и юге.

In [33]:
from_north = df[df['region'] == 'North']['annual_income']
from_south =  df[df['region'] == 'South']['annual_income']
fig = go.Figure()
fig.add_trace(go.Histogram(x=from_north, name='From North'))
fig.add_trace(go.Histogram(x=from_south, name='From South'))
fig.update_xaxes(title_text='annual income')
fig.update_yaxes(title_text='count')

4. Постройте box plot отображающий распределение уровня лояльности для людей до 20 лет, от 20 до 40, от 40 до 60 и старше 60 лет

In [34]:
t20 = df[df['age'] < 20]
f20t40 = df[(20 <= df['age']) & (df['age'] < 40)]
f40t60 = df[(40 <= df['age']) & (df['age'] < 60)]
f60 = df[60 <= df['age']]

fig = go.Figure()
fig.add_trace(go.Bar(
    x=['< 20'],
    y=[t20['loyalty_score'].mean()],
    name='under 20'
))
fig.add_trace(go.Bar(
    x=['20-40'],
    y=[f20t40['loyalty_score'].mean()],
    name='from 20 to 40'
))
fig.add_trace(go.Bar(
    x=['40-60'],
    y=[f40t60['loyalty_score'].mean()],
    name='from 40 to 60'
))
fig.add_trace(go.Bar(
    x=['> 60'],
    y=[f60['loyalty_score'].mean()],
    name='over 60'
))
fig.update_xaxes(title_text='age category')
fig.update_yaxes(title_text='average loyalty score')
fig.show()


5. Визуализируйте зависимость частоты покупок от заработка

In [35]:
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=df['annual_income'],
    y=df['purchase_frequency'],
    mode='markers'
))
fig.update_xaxes(title_text='annual income')
fig.update_yaxes(title_text='purchase frequency')
fig.show()

6. Визуализируйте как зависит сумма покупок от зарплаты клиента

In [36]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df['annual_income'],
    y=df['purchase_amount'],
    mode='markers'
))
fig.update_xaxes(title_text='annual income')
fig.update_yaxes(title_text='purchase amount')
fig.show()

7. Придумайте как визуализировать зависимость между частотой покупок, суммой покупок и скором лояльности *

\* Задание на доп. балл

In [56]:
def define_color_by_purchase_amount(pa: int):
    h = pa*255//640
    return '#0000' + ('' if h >= 16 else '0') + hex(h)[2:]

fig = go.Figure()
for index, row in df.iterrows():
    fig.add_trace(go.Scatter(
        x=[row['purchase_frequency']],
        y=[row['loyalty_score']],
        mode='markers',
        marker_color=define_color_by_purchase_amount(row['purchase_amount'])
    ))

fig.update_xaxes(title_text='purchase frequency')
fig.update_yaxes(title_text='loyalty score')
fig.update_layout(showlegend=False)
fig.show()
